<a href="https://colab.research.google.com/github/The237/DeepLearningCourses/blob/main/02_01_Recreer_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [26]:
class Box():
  def __init__(self):
    pass

  def forward(self, inputs):
    self.inputs = inputs
    self.output = self.operation()

    return self.output

  def backward(self, derivee_output):
    assert derivee_output.shape == self.output.shape, f'La dérivée output reçue a un shape {derivee_output.shape} et différent du shape de output : {self.output.shape}'

    assert self.derivee_inputs.shape == self.inputs.shape, f'La dérivée input calculée a un shape {self.derivee_input.shape} et différent du shape de input : {self.inputs.shape}'
    self.derivee_inputs = self.gradient(derivee_output)

    return self.derivee_inputs

  def operation(self):
    pass

  def gradient(self,derivee_output):
    pass

In [27]:
class BoxParams():
  def __init__(self, param):
    self.param = param
    pass

  def forward(self, inputs):
    self.inputs = inputs
    self.output = self.operation()

    return self.output

  def backward(self, derivee_output):

    assert derivee_output.shape == self.output.shape, f'La dérivée output reçue a un shape {derivee_output.shape} et différent du shape de output : {self.output.shape}'

    self.derivee_inputs = self.gradient(derivee_output)
    assert self.derivee_inputs.shape == self.inputs.shape, f'La dérivée input calculée a un shape {self.derivee_input.shape} et différent du shape de input : {self.inputs.shape}'

    self.derivee_param = self.gradient_param(derivee_output)
    assert self.derivee_param.shape == self.param.shape, f'La dérivée de param a un shape {self.derivee_param.shape} et différent du shape de param : {self.param.shape}'

    return self.derivee_inputs

  def operation(self):
    pass

  def gradient(self,derivee_output):
    pass

  def gradient_param(self,derivee_output):
    pass

# La Classe Dot

In [46]:
class Dot(BoxParams):

  def __init__(self, weights):
    super().__init__(weights)

  def operation(self):
    return np.dot(self.inputs, self.param)

  def gradient(self, derivee_output):
     return np.dot(derivee_output,self.param.T)

  def gradient_param(self, derivee_output):
     return np.dot(self.inputs.T, derivee_output)

  def __repr__(self):
    return "Dot Product"

In [29]:
X = np.array([
    [2,3,-2],
    [4,5,-1],
    [-5,2,3],
    [0,5,4]
])

In [30]:
W = np.array([
    [.4967],
    [-.1383],
    [.6477]
])

In [31]:
np.dot(X,W)

array([[-0.7169],
       [ 0.6476],
       [-0.817 ],
       [ 1.8993]])

In [47]:
M = Dot(weights=W)

In [48]:
out = M.forward(X)
out

array([[-0.7169],
       [ 0.6476],
       [-0.817 ],
       [ 1.8993]])

In [44]:
d_out = np.random.randn(4,1)
d_out

array([[ 0.24803123],
       [-0.20806854],
       [ 0.55885881],
       [-0.79934479]])

In [49]:
M.backward(d_out)

array([[ 0.12319711, -0.03430272,  0.16064983],
       [-0.10334764,  0.02877588, -0.13476599],
       [ 0.27758517, -0.07729017,  0.36197285],
       [-0.39703456,  0.11054938, -0.51773562]])